export default [
  {
    name: 'United States',
    code: 'USA',
    region: 'Americas',
    index: ['Dow 30', 'S&P 500', 'Nasdaq', 'SmallCap 2000', 'S&P 500 VIX'],
  },
  {
    name: 'Canada',
    code: 'CAN',
    region: 'Americas',
    index: ['S&P/TSX', 'TR Canada 50'],
  },
  {
    name: 'Brazil',
    code: 'BRA',
    region: 'Americas',
    index: ['Bovespa'],
  },
  {
    name: 'Mexico',
    code: 'MEX',
    region: 'Americas',
    index: ['S&P/BMV IPC'],
  },
  {
    name: 'Germany',
    code: 'DEU',
    region: 'Europe',
    index: ['DAX'],
  },
  {
    name: 'United Kingdom',
    code: 'GBR',
    region: 'Europe',
    index: ['FTSE 100'],
  },
  {
    name: 'France',
    code: 'FRA',
    region: 'Europe',
    index: ['CAC 40'],
  },
  {
    name: 'Euro Zone',
    code: 'EUR',
    region: 'Europe',
    index: ['EURO Stoxx 50'],
  },
  {
    name: 'Netherlands',
    code: 'NLD',
    region: 'Europe',
    index: ['AEX'],
  },
  {
    name: 'Spain',
    code: 'ESP',
    region: 'Europe',
    index: ['IBEX 35'],
  },
  {
    name: 'Italy',
    code: 'ITA',
    region: 'Europe',
    index: ['FTSE MIB'],
  },
  {
    name: 'Switzerland',
    code: 'CHE',
    region: 'Europe',
    index: ['SMI'],
  },
  {
    name: 'Portugal',
    code: 'PRT',
    region: 'Europe',
    index: ['PSI 20'],
  },
  {
    name: 'Belgium',
    code: 'BEL',
    region: 'Europe',
    index: ['BEL 20'],
  },
  {
    name: 'Austria',
    code: 'AUT',
    region: 'Europe',
    index: ['ATX'],
  },
  {
    name: 'Sweden',
    code: 'SWE',
    region: 'Europe',
    index: ['OMXS30'],
  },
  {
    name: 'Denmark',
    code: 'DNK',
    region: 'Europe',
    index: ['OMXC20'],
  },
  {
    name: 'Russia',
    code: 'RUS',
    region: 'Europe',
    index: ['MOEX', 'RTSI'],
  },
  {
    name: 'Hungary',
    code: 'HUN',
    region: 'Europe',
    index: ['Budapest SE'],
  },
  {
    name: 'Poland',
    code: 'POL',
    region: 'Europe',
    index: ['WIG20'],
  },
  {
    name: 'Turkey',
    code: 'TUR',
    region: 'Asia',
    index: ['BIST 100'],
  },
  {
    name: 'Israel',
    code: 'ISR',
    region: 'Asia',
    index: ['TA 35'],
  },
  {
    name: 'Saudi Arabia',
    code: 'SAU',
    region: 'Asia',
    index: ['Tadawul All Share'],
  },
  {
    name: 'Japan',
    code: 'JPN',
    region: 'Asia',
    index: ['Nikkei 225'],
  },
  {
    name: 'Australia',
    code: 'AUS',
    region: 'Oceania',
    index: ['S&P/ASX 200', 'DJ New Zealand'],
  },
  {
    name: 'China',
    code: 'CHN',
    region: 'Asia',
    index: ['Shanghai', 'SZSE Component', 'China A50', 'DJ Shanghai'],
  },
  {
    name: 'Hong Kong',
    code: 'HKG',
    region: 'Asia',
    index: ['Hang Seng'],
  },
  {
    name: 'Taiwan',
    code: 'TWN',
    region: 'Asia',
    index: ['Taiwan Weighted'],
  },
  {
    name: 'Thailand',
    code: 'THA',
    region: 'Asia',
    index: ['SET'],
  },
  {
    name: 'South Korea',
    code: 'KOR',
    region: 'Asia',
    index: ['KOSPI'],
  },
  {
    name: 'Indonesia',
    code: 'IDN',
    region: 'Asia',
    index: ['IDX Composite'],
  },
  {
    name: 'India',
    code: 'IND',
    region: 'Asia',
    index: ['Nifty 50', 'BSE Sensex'],
  },
  {
    name: 'Philippines',
    code: 'PHL',
    region: 'Asia',
    index: ['PSEi Composite'],
  },
  {
    name: 'Singapore',
    code: 'SGP',
    region: 'Asia',
    index: ['STI Index'],
  },
  {
    name: 'Pakistan',
    code: 'PAK',
    region: 'Asia',
    index: ['Karachi 100'],
  },
  {
    name: 'Vietnam',
    code: 'VNM',
    region: 'Asia',
    index: ['HNK 30'],
  },
  {
    name: 'Sri Lanka',
    code: 'LKA',
    region: 'Asia',
    index: ['CSE All-Share'],
  },
];
