export default [
  {
    name: 'United States',
    code: 'USA',
    region: 'Americas',
    index: ['Dow 30', 'S&P 500', 'Nasdaq', 'SmallCap 2000', 'S&P 500 VIX'],
    currency: 'USD',
    currencyIcon: '$',
  },
  {
    name: 'Canada',
    code: 'CAN',
    region: 'Americas',
    index: ['S&P/TSX', 'TR Canada 50'],
    currency: 'CAD',
    currencyIcon: '$',
  },
  {
    name: 'Brazil',
    code: 'BRA',
    region: 'Americas',
    index: ['Bovespa'],
    currency: 'BRL',
    currencyIcon: 'R$',
  },
  {
    name: 'Mexico',
    code: 'MEX',
    region: 'Americas',
    index: ['S&P/BMV IPC'],
    currency: 'MXN',
    currencyIcon: '$',
  },
  {
    name: 'Germany',
    code: 'DEU',
    region: 'Europe',
    index: ['DAX'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'United Kingdom',
    code: 'GBR',
    region: 'Europe',
    index: ['FTSE 100'],
    currency: 'GBP',
    currencyIcon: '£',
  },
  {
    name: 'France',
    code: 'FRA',
    region: 'Europe',
    index: ['CAC 40'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Euro Zone',
    code: 'EUR',
    region: 'Europe',
    index: ['EURO Stoxx 50'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Netherlands',
    code: 'NLD',
    region: 'Europe',
    index: ['AEX'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Spain',
    code: 'ESP',
    region: 'Europe',
    index: ['IBEX 35'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Italy',
    code: 'ITA',
    region: 'Europe',
    index: ['FTSE MIB'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Switzerland',
    code: 'CHE',
    region: 'Europe',
    index: ['SMI'],
    currency: 'CHF',
    currencyIcon: 'CHF',
  },
  {
    name: 'Portugal',
    code: 'PRT',
    region: 'Europe',
    index: ['PSI 20'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Belgium',
    code: 'BEL',
    region: 'Europe',
    index: ['BEL 20'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Austria',
    code: 'AUT',
    region: 'Europe',
    index: ['ATX'],
    currency: 'EUR',
    currencyIcon: '€',
  },
  {
    name: 'Sweden',
    code: 'SWE',
    region: 'Europe',
    index: ['OMXS30'],
    currency: 'SEK',
    currencyIcon: 'kr',
  },
  {
    name: 'Denmark',
    code: 'DNK',
    region: 'Europe',
    index: ['OMXC20'],
    currency: 'DKK',
    currencyIcon: 'kr',
  },
  {
    name: 'Russia',
    code: 'RUS',
    region: 'Europe',
    index: ['MOEX', 'RTSI'],
    currency: 'RUB',
    currencyIcon: '₽',
  },
  {
    name: 'Hungary',
    code: 'HUN',
    region: 'Europe',
    index: ['Budapest SE'],
    currency: 'HUF',
    currencyIcon: 'Ft',
  },
  {
    name: 'Poland',
    code: 'POL',
    region: 'Europe',
    index: ['WIG20'],
    currency: 'PLN',
    currencyIcon: 'zł',
  },
  {
    name: 'Turkey',
    code: 'TUR',
    region: 'Asia',
    index: ['BIST 100'],
    currency: 'TRY',
    currencyIcon: '₺',
  },
  {
    name: 'Israel',
    code: 'ISR',
    region: 'Asia',
    index: ['TA 35'],
    currency: 'ILS',
    currencyIcon: '₪',
  },
  {
    name: 'Saudi Arabia',
    code: 'SAU',
    region: 'Asia',
    index: ['Tadawul All Share'],
    currency: 'SAR',
    currencyIcon: '﷼',
  },
  {
    name: 'Japan',
    code: 'JPN',
    region: 'Asia',
    index: ['Nikkei 225'],
    currency: 'JPY',
    currencyIcon: '¥',
  },
  {
    name: 'Australia',
    code: 'AUS',
    region: 'Oceania',
    index: ['S&P/ASX 200', 'DJ New Zealand'],
    currency: 'AUD',
    currencyIcon: '$',
  },
  {
    name: 'China',
    code: 'CHN',
    region: 'Asia',
    index: ['Shanghai', 'SZSE Component', 'China A50', 'DJ Shanghai'],
    currency: 'CNY',
    currencyIcon: '¥',
  },
  {
    name: 'Hong Kong',
    code: 'HKG',
    region: 'Asia',
    index: ['Hang Seng'],
    currency: 'HKD',
    currencyIcon: '$',
  },
  {
    name: 'Taiwan',
    code: 'TWN',
    region: 'Asia',
    index: ['Taiwan Weighted'],
    currency: 'TWD',
    currencyIcon: 'NT$',
  },
  {
    name: 'Thailand',
    code: 'THA',
    region: 'Asia',
    index: ['SET'],
    currency: 'THB',
    currencyIcon: '฿',
  },
  {
    name: 'South Korea',
    code: 'KOR',
    region: 'Asia',
    index: ['KOSPI'],
    currency: 'KPW',
    currencyIcon: '₩',
  },
  {
    name: 'Indonesia',
    code: 'IDN',
    region: 'Asia',
    index: ['IDX Composite'],
    currency: 'IDR',
    currencyIcon: 'Rp',
  },
  {
    name: 'India',
    code: 'IND',
    region: 'Asia',
    index: ['Nifty 50', 'BSE Sensex'],
    currency: 'INR',
    currencyIcon: '₹',
  },
  {
    name: 'Philippines',
    code: 'PHL',
    region: 'Asia',
    index: ['PSEi Composite'],
    currency: 'PHP',
    currencyIcon: '₱',
  },
  {
    name: 'Singapore',
    code: 'SGP',
    region: 'Asia',
    index: ['STI Index'],
    currency: 'SGD',
    currencyIcon: '$',
  },
  {
    name: 'Pakistan',
    code: 'PAK',
    region: 'Asia',
    index: ['Karachi 100'],
    currency: 'PKR',
    currencyIcon: '₨',
  },
  {
    name: 'Vietnam',
    code: 'VNM',
    region: 'Asia',
    index: ['HNK 30'],
    currency: 'VND',
    currencyIcon: '₫',
  },
  {
    name: 'Sri Lanka',
    code: 'LKA',
    region: 'Asia',
    index: ['CSE All-Share'],
    currency: 'LKR',
    currencyIcon: 'Rs',
  },
];
