export const SEARCH_ITEM_IN_STOCK_REQUEST = 'SEARCH_ITEM_IN_STOCK_REQUEST';
export const SEARCH_ITEM_IN_STOCK_SUCCESS = 'SEARCH_ITEM_IN_STOCK_SUCCESS';
export const SEARCH_ITEM_IN_STOCK_ERROR = 'SEARCH_ITEM_IN_STOCK_ERROR';

export const GET_ITEM_RATES_REQUEST = 'GET_ITEM_RATES_REQUEST';
export const GET_ITEM_RATES_SUCCESS = 'GET_ITEM_RATES_SUCCESS';
export const GET_ITEM_RATES_ERROR = 'GET_ITEM_RATES_ERROR';

export const GET_ITEM_RATES_HISTORY_REQUEST = 'GET_ITEM_RATES_HISTORY_REQUEST';
export const GET_ITEM_RATES_HISTORY_SUCCESS = 'GET_ITEM_RATES_HISTORY_SUCCESS';
export const GET_ITEM_RATES_HISTORY_ERROR = 'GET_ITEM_RATES_HISTORY_ERROR';

export const GET_LOCAL_ITEM_LIST_REQUEST = 'GET_LOCAL_ITEM_LIST_REQUEST';
export const GET_LOCAL_ITEM_LIST_SUCCESS = 'GET_LOCAL_ITEM_LIST_SUCCESS';
export const GET_LOCAL_ITEM_LIST_ERROR = 'GET_LOCAL_ITEM_LIST_ERROR';

export const SET_LOCAL_ITEM_LIST_REQUEST = 'SET_LOCAL_ITEM_LIST_REQUEST';
export const SET_LOCAL_ITEM_LIST_SUCCESS = 'SET_LOCAL_ITEM_LIST_SUCCESS';
export const SET_LOCAL_ITEM_LIST_ERROR = 'SET_LOCAL_ITEM_LIST_ERROR';

export const GET_CRYPTO_LIST_REQUEST = 'GET_CRYPTO_LIST_REQUEST';
export const GET_CRYPTO_LIST_SUCCESS = 'GET_CRYPTO_LIST_SUCCESS';
export const GET_CRYPTO_LIST_ERROR = 'GET_CRYPTO_LIST_ERROR';

export const GET_CRYPTO_ITEM_RATES_REQUEST = 'GET_CRYPTO_ITEM_RATES_REQUEST';
export const GET_CRYPTO_ITEM_RATES_SUCCESS = 'GET_CRYPTO_ITEM_RATES_SUCCESS';
export const GET_CRYPTO_ITEM_RATES_ERROR = 'GET_CRYPTO_ITEM_RATES_ERROR';
