export const SEARCH_ITEM_IN_STOCK_REQUEST = 'SEARCH_ITEM_IN_STOCK_REQUEST';
export const SEARCH_ITEM_IN_STOCK_SUCCESS = 'SEARCH_ITEM_IN_STOCK_SUCCESS';
export const SEARCH_ITEM_IN_STOCK_ERROR = 'SEARCH_ITEM_IN_STOCK_ERROR';

export const GET_ITEM_RATES_REQUEST = 'GET_ITEM_RATES_REQUEST';
export const GET_ITEM_RATES_SUCCESS = 'GET_ITEM_RATES_SUCCESS';
export const GET_ITEM_RATES_ERROR = 'GET_ITEM_RATES_ERROR';

export const GET_ITEM_RATES_HISTORY_REQUEST = 'GET_ITEM_RATES_HISTORY_REQUEST';
export const GET_ITEM_RATES_HISTORY_SUCCESS = 'GET_ITEM_RATES_HISTORY_SUCCESS';
export const GET_ITEM_RATES_HISTORY_ERROR = 'GET_ITEM_RATES_HISTORY_ERROR';

export const GET_LOCAL_ITEM_LIST_REQUEST = 'GET_LOCAL_ITEM_LIST_REQUEST';
export const GET_LOCAL_ITEM_LIST_SUCCESS = 'GET_LOCAL_ITEM_LIST_SUCCESS';
export const GET_LOCAL_ITEM_LIST_ERROR = 'GET_LOCAL_ITEM_LIST_ERROR';

export const SET_LOCAL_ITEM_LIST_REQUEST = 'SET_LOCAL_ITEM_LIST_REQUEST';
export const SET_LOCAL_ITEM_LIST_SUCCESS = 'SET_LOCAL_ITEM_LIST_SUCCESS';
export const SET_LOCAL_ITEM_LIST_ERROR = 'SET_LOCAL_ITEM_LIST_ERROR';

// export const ADD_TO_LOCAL_ITEM_LIST_REQUEST = 'ADD_TO_LOCAL_ITEM_LIST_REQUEST';
// export const ADD_TO_LOCAL_ITEM_LIST_SUCCESS = 'ADD_TO_LOCAL_ITEM_LIST_SUCCESS';
// export const ADD_TO_LOCAL_ITEM_LIST_ERROR = 'ADD_TO_LOCAL_ITEM_LIST_ERROR';
//
// export const DELETE_FROM_LOCAL_ITEM_LIST_REQUEST = 'DELETE_FROM_LOCAL_ITEM_LIST_REQUEST';
// export const DELETE_FROM_LOCAL_ITEM_LIST_SUCCESS = 'DELETE_FROM_LOCAL_ITEM_LIST_SUCCESS';
// export const DELETE_FROM_LOCAL_ITEM_LIST_ERROR = 'DELETE_FROM_LOCAL_ITEM_LIST_ERROR';
